### ISSUE TITLE
handle Chinese characters

### ISSUE THREAD

**Issue by cattyhouse** [denisidoro/navi#712] opened 2022-04-05 15:23 UTC
if the comment row has Chinese characters, the third row does not align correctly.
![2022-04-05 23 24 39](https://user-images.githubusercontent.com/3365320/161789091-c5042938-be50-47f0-a016-b10437bbebe3.jpg)

**Comment by denisidoro** [comment] 2022-04-06 21:30
I bet the problem is in [this line](https://github.com/denisidoro/navi/blob/77403ca0e55c84219fd9980208727078c062ade9/src/writer.rs#L35) and is related to the fact that chinese characters need more than 1 byte to be represented.

This will also happen if you try using emojis too, I presume.

I need to investigate it

**Comment by cattyhouse** [comment] 2022-04-07 06:25
> I bet the problem is in [this line](https://github.com/denisidoro/navi/blob/77403ca0e55c84219fd9980208727078c062ade9/src/writer.rs#L35) and is related to the fact that chinese characters need more than 1 byte to be represented.
> 
> This will also happen if you try using emojis too, I presume.
> 
> I need to investigate it

Many thanks

**Comment by mauricelam** [comment] 2023-01-05 10:06
I ran into this issue as well. Looks like `format!()` is padding it to the correct number of characters, but the problem is that those Chinese characters are simply rendered twice as wide by the terminal. The [unicode-width](https://github.com/unicode-rs/unicode-width) crate can probably help.

**Comment by denisidoro** [comment] 2023-04-08 23:54
Duplicate of #820

**Closed by denisidoro** 2023-04-08 23:54 UTC
Labels: bug
