### ISSUE TITLE
Use variable defined in cheat in another cheat  

### ISSUE THREAD

**Issue by plaip** [denisidoro/navi#378] opened 2020-08-13 20:13 UTC
### Is your feature request related to a problem?
In my cheats, I have duplicated variables (ie: path or helpers). 

**A.cheat** 
```
# Print variable content
echo <variable_a>
echo <variable_b>

$ variable_a: foo
$ variable_b: bar
```
**B.cheat** 
```
# Print variable content
echo "<variable_a> - <variable_b>"

$ variable_a: foo
$ variable_b: bar
```

### Describe the solution you'd like
Use a common or helpers cheat to declare all common variables between all cheats. 

**Common.cheat** 
```
# Declare all common variables in a this cheat.
$ variable_a: foo
$ variable_b: bar
```
**A.cheat** 
```
# Use a trigger word to include cheat in another cheat (ie: include or something else)
include  common.cheat

# Print variable content
echo <variable_a>
echo <variable_b>
```
**B.cheat** 
```
# Use a trigger word to include cheat in another cheat.
include  common.cheat

# Print variable content
echo "<variable_a> - <variable_b>"
```

Please feel free to comment this feature request if not clear.

**Comment by denisidoro** [comment] 2020-08-14 12:52
Duplicate of #377

**Closed by denisidoro** 2020-08-14 12:52 UTC
Labels: new feature
