### ISSUE TITLE
Can't turn off exact mode when using skim

### ISSUE THREAD

**Issue by itmecho** [denisidoro/navi#363] opened 2020-05-28 11:53 UTC
**Is your feature request related to a problem? Please describe.**
See #232 for the same issue with `fzf`. We worked around that by using the overrides and setting `--no-exact`, however `skim` doesn't have that flag so there is no way to turn this off. I feel like setting `--exact` is removing the main benefit of fuzzy searching and just turning it into a normal search.

**Describe the solution you'd like**
Some method of disabling `--exact` for `skim` or ideally, don't set exact as a default as it removes the fuzzy searching capabilities of the finders.

**Describe alternatives you've considered**
Make `exact` mode not the default. You can add `--exact` using the override flags/env vars but you can't remove it for `skim`

**Comment by denisidoro** [comment] 2020-05-28 20:10
The problem is that changing this would be a "breaking" change from my standpoint. Users may be used to the current behavior. `navi best` may break depend on the query used.

I think we could add something like this to [this line](https://github.com/denisidoro/navi/blob/6678cda0322406c75a97a5977491352acef870bb/src/finder/skim.rs#L34):
```rust
let mut makeExact = true;

if let Some(o) = opts.overrides {
    if o.includes("--no-exact") {
        makeExact = false;
    }
}

// ...

if makeExact {
    command.arg("--exact");
}
```

WDYT?

**Comment by itmecho** [comment] 2020-05-28 20:16
That makes sense. That change works for me as long as the overrides include the ones set as environment variables =]

**Comment by denisidoro** [comment] 2020-05-28 20:43
It includes.

Do you think you'd be able to open a PR with this? As soon as I merge it, I can release a new version.

**Comment by itmecho** [comment] 2020-05-28 20:56
Sure! I'll take a look at it tomorrow

**Comment by itmecho** [comment] 2020-05-29 08:03
Having done the PR for this, it feels a little hacky. What are your thoughts on having a new flag/environment variable `--exact`/`NAVI_EXACT` which defaults to true to controls this? That way we don't have to filter the overrides for a flag that isn't supported by the finder

**Comment by denisidoro** [comment] 2020-05-29 12:18
Your call. I merged your PR for the time being.

Please let me know if you want to follow the `--exact` arg. In this case I'll wait for another PR of yours to release a new version. Otherwise, I'll release a new version as-is.

Oh, thank you for your contribution! 👍

**Comment by itmecho** [comment] 2020-05-30 21:56
Hmm seems like structopt doesn't support `env` for flags. I guess the current way works for now!

Thanks for accepting it =]

**Closed** 2020-06-08 20:39 UTC
Labels: new feature

**Comment by eugenesvk** [comment] 2023-03-12 12:40
This doesn't seem to work for me
this works
```
$NAVI_FZF_OVERRIDES='--exact'; navi --finder skim
```

this fails
```
$NAVI_FZF_OVERRIDES='--no-exact'; navi --finder skim
```
with
> error: Found argument '--no-exact' which wasn't expected, or isn't valid in this context
> Did you mean '--exact'?
> If you tried to supply `--no-exact` as a value rather than a flag, use `-- --no-exact`

but this also failed
```
$NAVI_FZF_OVERRIDES='-- --no-exact'; navi --finder skim
```

So what is the config knob to turn to enable fuzzy search with skim?
