### ISSUE TITLE
Unable to import custom cheats

### ISSUE THREAD

**Issue by sujitawake** [denisidoro/navi#725] opened 2022-05-10 09:01 UTC
After adding my custom github repo path in `featured_repo.txt` file, whenever I execute the command `navi repo browse`, navi is not showing the cheats which I've added into the github repo.

Am I doing anything wrong here to import the remote repo cheats?

**Expected behavior**
It should show `mytest` folder in console while typing.

**Screenshots**
Here is a quick terminal cast (ignore the weird looking characters in the prompt)
https://asciinema.org/a/493322

**Versions:**
 - OS: Kali Linux
 - Shell: zsh

**Additional context**
This is the [URL](https://github.com/sujit/tmp) where I've added a dummy cheat file that I am trying to import.

**Comment by lacygoill** [comment] 2022-05-10 22:04
> Am I doing anything wrong here to import the remote repo cheats?

I could be wrong, but I think you're supposed to:

   - fork the [denisidoro/cheats](https://github.com/denisidoro/cheats) repo
   - edit [the featured_repos.txt](https://github.com/denisidoro/cheats/blob/master/featured_repos.txt) file so that it includes the name of your cheats repo
   - open a PR for the change to be merged

At least that's my understanding based on the [documentation](https://github.com/denisidoro/navi/blob/master/docs/cheatsheet_repositories.md#submitting-cheatsheets).

This seems to be confirmed by `strace(1)`:

    $ rm -rf ~/.local/share/navi/cheats/tmp/ \
        ; strace -e trace=openat --output=/tmp/trace.log navi repo browse \
        ; less /tmp/trace.log

The only `featured_repos.txt` file which navi reads is:

    $HOME/.local/share/navi/cheats/tmp/featured/featured_repos.txt

And not:

    $HOME/.local/share/navi/cheats/featured_repos.txt

And you can't use the former file to write your repo:

    $ rm -rf ~/.local/share/navi/cheats/tmp/ \
        ; strace --string-limit=256 -e trace=write --output=/tmp/trace.log navi repo browse \
        ; less /tmp/trace.log

The trace is:

    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=124668, si_uid=1000, si_status=0, si_utime=1, si_stime=0} ---
    write(4, "denisidoro/cheats\ndenisidoro/navi-tldr-pages\ndenisidoro/dotfiles\nmrVanDalo/navi-cheats\nchazeon/my-navi-cheats\ncaojianhua/MyCheat\nKidman1670/cheats\nisene/cheats\nm42martin/navi-cheats\ninfosecstreams/cheat.sheets\n", 210) = 210
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=124675, si_uid=1000, si_status=130, si_utime=0, si_stime=0} ---
    +++ exited with 130 +++

This says that navi executes the `write(2)` system call to write this multi-line string in the `featured_repo.txt` file:

    denisidoro/cheats
    denisidoro/navi-tldr-pages
    denisidoro/dotfiles
    mrVanDalo/navi-cheats
    chazeon/my-navi-cheats
    caojianhua/MyCheat
    Kidman1670/cheats
    isene/cheats
    m42martin/navi-cheats
    infosecstreams/cheat.sheets

IOW, whatever you wrote in it, navi doesn't care and overwrite it.

---

FWIW, here is how I manage [my local cheat sheets](https://github.com/lacygoill/config/tree/master/.local/share/navi/cheats/mine).  I put them in `$(navi info cheats-path)/mine` (that is `~/.local/share/navi/cheats/mine`), and version control them alongside the rest of my config files.

Then, [I bind `C-g C-g`](https://github.com/lacygoill/config/blob/c3fe8aef8e4f6f433cb69c6100931c6dd0c1c612/.config/fish/config.fish#L208) to [this fish function](https://github.com/lacygoill/config/blob/master/.config/fish/functions/cheat-sheets.fish):
```fish
set _my_cheat_sheets "$(navi info cheats-path)"/mine

function cheat-sheets
    set -f current_process $(commandline --current-process)
    set -f leading_whitespace $(string match --regex -- '^\s*' $current_process)
    set -f current_process $(string trim -- $current_process)

    set -f options --print --path=$_my_cheat_sheets

    if test -z "$current_process"
        commandline --insert $(navi $options)
        commandline --function repaint
        return
    end

    set -f snippet $(navi $options --query="$current_process")
    commandline --replace --current-process "$(string join -- '' $leading_whitespace $snippet)"
    commandline --function repaint
end
```
Notice that the function evaluates `$(navi info cheats-path)/mine` to get the path to my local cheats programmatically.

Anyway, if your goal is to maintain your cheats on github, this *might* be a way to do it.

**Comment by denisidoro** [comment] 2022-05-15 15:18
The change in `featured_repo.txt` is necessary only to make featured cheatsheet repositories available to everyone when they enter `navi repo browse`.

In your case you just need to add `export NAVI_PATH="/some/custom/path` to your `.bashrc`-like file or add cheatsheets directly to `navi info cheats-path`

**Closed by denisidoro** 2022-05-15 15:18 UTC
