### ISSUE TITLE
Error while trying to install from cargo

### ISSUE THREAD

**Issue by george-gca** [denisidoro/navi#608] opened 2021-08-23 00:18 UTC
**Describe the bug**
Error while trying to install from [cargo](https://github.com/denisidoro/navi/blob/master/docs/installation.md#using-cargo) or [install script](https://github.com/denisidoro/navi/blob/master/docs/installation.md#using-install-script). Both give the same error.

**To Reproduce**
Just run the required installation code.

**Expected behavior**
To install it.

**Screenshots**
```
$ cargo install navi
    Updating crates.io index
  Installing navi v2.17.0
   Compiling libc v0.2.100
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.75
   Compiling version_check v0.9.3
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling autocfg v1.0.1
   Compiling ppv-lite86 v0.2.10
   Compiling signal-hook v0.3.9
   Compiling serde_derive v1.0.128
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.128
   Compiling smallvec v1.6.1
   Compiling unicode-segmentation v1.8.0
   Compiling hashbrown v0.11.2
   Compiling bitflags v1.3.2
   Compiling utf8parse v0.1.1
   Compiling regex-syntax v0.6.25
   Compiling lazy_static v1.4.0
   Compiling anyhow v1.0.43
   Compiling either v1.6.1
   Compiling linked-hash-map v0.5.4
   Compiling remove_dir_all v0.5.3
   Compiling unicode-width v0.1.8
   Compiling termcolor v1.1.2
   Compiling same-file v1.0.6
   Compiling dtoa v0.4.8
   Compiling os_str_bytes v3.1.0
   Compiling vec_map v0.8.2
   Compiling strsim v0.10.0
   Compiling instant v0.1.10
   Compiling lock_api v0.4.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling vte v0.3.3
   Compiling indexmap v1.7.0
   Compiling textwrap v0.14.2
   Compiling yaml-rust v0.4.5
   Compiling walkdir v2.3.2
   Compiling heck v0.3.3
   Compiling strip-ansi-escapes v0.1.0
   Compiling aho-corasick v0.7.18
   Compiling quote v1.0.9
   Compiling getrandom v0.2.3
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.7.13
   Compiling parking_lot_core v0.8.3
   Compiling atty v0.2.14
   Compiling which v4.2.2
   Compiling dirs-sys-next v0.1.2
   Compiling remove_dir_all v0.7.0
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.1
   Compiling regex v1.5.4
   Compiling directories-next v2.0.0
   Compiling rand_chacha v0.3.1
   Compiling signal-hook-mio v0.2.1
   Compiling shellwords v1.1.0
   Compiling rand v0.8.4
   Compiling crossterm v0.20.0
   Compiling tempfile v3.2.0
   Compiling edit v0.1.3
   Compiling thiserror-impl v1.0.26
   Compiling clap_derive v3.0.0-beta.4
   Compiling thiserror v1.0.26
   Compiling clap v3.0.0-beta.4
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `navi v2.17.0`, intermediate artifacts can be found at `/tmp/cargo-installph3cZ6`

Caused by:
  build failed
```

**Versions:**
 - OS: Ubuntu 21.04
 - Shell Version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
 - Cargo Version: 1.51.0

**Additional context**
Installed cargo via apt-get. Successfully installed other stuff via cargo.

**Comment by denisidoro** [comment] 2021-08-23 12:08
> README.md
My bad. I'll fix it.

> unstable feature
[Apparently](https://doc.rust-lang.org/std/ffi/struct.OsString.html#method.eq_ignore_ascii_case), you need Rust stable 1.53+ to use this feature, or older Rust unstable versions.
I guess I'll downgrade `clap` to make this requirement looser.

**Comment by denisidoro** [comment] 2021-08-23 12:09
I guess I'll downgrade `clap` to fix these issues.

**Comment by denisidoro** [comment] 2021-08-23 12:17
Does it work now?

https://crates.io/crates/navi/2.17.1

**Comment by george-gca** [comment] 2021-08-23 14:41
Still throwing error:
```
$ cargo install navi
    Updating crates.io index
  Downloaded navi v2.17.1
  Downloaded 1 crate (57.6 KB) in 2.19s
  Installing navi v2.17.1
   Compiling libc v0.2.100
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.75
   Compiling version_check v0.9.3
   Compiling autocfg v1.0.1
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling serde_derive v1.0.128
   Compiling signal-hook v0.3.9
   Compiling ppv-lite86 v0.2.10
   Compiling hashbrown v0.11.2
   Compiling serde v1.0.128
   Compiling unicode-segmentation v1.8.0
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.6.1
   Compiling either v1.6.1
   Compiling linked-hash-map v0.5.4
   Compiling bitflags v1.3.2
   Compiling anyhow v1.0.43
   Compiling unicode-width v0.1.8
   Compiling utf8parse v0.1.1
   Compiling regex-syntax v0.6.25
   Compiling remove_dir_all v0.5.3
   Compiling lazy_static v1.4.0
   Compiling dtoa v0.4.8
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling same-file v1.0.6
   Compiling vec_map v0.8.2
   Compiling os_str_bytes v3.1.0
   Compiling instant v0.1.10
   Compiling lock_api v0.4.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.7.0
   Compiling yaml-rust v0.4.5
   Compiling textwrap v0.14.2
   Compiling vte v0.3.3
   Compiling walkdir v2.3.2
   Compiling heck v0.3.3
   Compiling strip-ansi-escapes v0.1.0
   Compiling aho-corasick v0.7.18
   Compiling quote v1.0.9
   Compiling getrandom v0.2.3
   Compiling signal-hook-registry v1.4.0
   Compiling parking_lot_core v0.8.3
   Compiling mio v0.7.13
   Compiling which v4.2.2
   Compiling dirs-sys-next v0.1.2
   Compiling atty v0.2.14
   Compiling remove_dir_all v0.7.0
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.1
   Compiling directories-next v2.0.0
   Compiling regex v1.5.4
   Compiling rand_chacha v0.3.1
   Compiling signal-hook-mio v0.2.1
   Compiling rand v0.8.4
   Compiling shellwords v1.1.0
   Compiling crossterm v0.20.0
   Compiling tempfile v3.2.0
   Compiling edit v0.1.3
   Compiling clap_derive v3.0.0-beta.4
   Compiling thiserror-impl v1.0.26
   Compiling thiserror v1.0.26
   Compiling clap v3.0.0-beta.4
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `navi v2.17.1`, intermediate artifacts can be found at `/tmp/cargo-installKHBwO3`

Caused by:
  build failed
```

**Comment by george-gca** [comment] 2021-08-23 15:01
> > README.md
> 
> I guess this is an error on clap's end.
> 
> > unstable feature
> 
> [Apparently](https://doc.rust-lang.org/std/ffi/struct.OsString.html#method.eq_ignore_ascii_case), you need Rust stable 1.53+ to use this feature, or older Rust unstable versions.

Apparently yes, just tried in another machine to update rust and install navi, and it worked fine.
My machine:
- OS: Ubuntu 21.04
- Shell Version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
- Cargo Version: 1.51.0

Working machine:
- OS: Ubuntu 20.04.2 LTS
- Shell Version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- Cargo Version: 1.54.0

Since I installed cargo from apt-get, then I must uninstall it, and reinstall from [rustup](https://www.rust-lang.org/tools/install) right?

**Comment by denisidoro** [comment] 2021-08-23 15:05
It's odd that in your last logs I still see clap beta4, even thought I downgraded it to beta2 in the 2.17.1 version 🤔

Maybe I forgot to update master before releasing the new version 🤔

**Comment by george-gca** [comment] 2021-08-23 15:47
I haven't updated my cargo version in my machine yet, so if you want to I can verify again if the instalation works.

**Comment by denisidoro** [comment] 2021-08-23 20:20
Would you mind cloning the repo and trying to run `cargo build` on it? 

If it works then edit `Cargo.toml` and bump `clap` back to `beta4` and trying building it again, just to confirm if it fails again.

Thanks!

**Comment by zouhair** [comment] 2021-08-24 02:46
> 
> 
> Would you mind cloning the repo and trying to run `cargo build` on it?
> 
> If it works then edit `Cargo.toml` and bump `clap` back to `beta4` and trying building it again, just to confirm if it fails again.
> 
> Thanks!

Building with `clap = "3.0.0-beta.2"` works and but breaks with `clap = "3.0.0-beta.4"`

**Comment by george-gca** [comment] 2021-08-24 15:37
@denisidoro here the build works with `clap = "3.0.0-beta.2"`, but fails with `"3.0.0-beta.4"`. Surprisingly though, when I change it to `"3.0.0-beta.3"` or `"3.0.0-beta.2"` it still shows `"3.0.0-beta.4"` during build, even though I did `cargo clean` before calling `cargo build` again.

**Comment by george-gca** [comment] 2021-08-24 15:54
Just checked that the `Cargo.lock` file is always being generated with `"3.0.0-beta.4"` even if I delete it. Tried to do `cargo update -p clap` and `cargo update`, still the build tries to use `clap v3.0.0-beta.4`.

**Comment by denisidoro** [comment] 2021-08-24 17:26
Thank you for troubleshooting it!

I was able to reproduce the problem.

I've just learned that in `Cargo.toml`, `"3.0.0-beta.2"` = `"^3.0.0-beta.2"`, which explains what you're saying.

The bad news is that I'm trying a lot of different configurations (such as `"<=3.0.0-beta.2"`) but I'm always getting the errors when trying to compile project.

**Comment by george-gca** [comment] 2021-08-24 18:12
> I've just learned that in Cargo.toml "3.0.0-beta.2" = "^3.0.0-beta.2", which explains what you're seeing.

This is actually bad. There should be some way to specify down to the smallest version detail available. Maybe it is the case to open a feature request for cargo?

But the thing is, I downloaded the clean repo, changed to `3.0.0-beta.2` and compiled it successfully. Later tried with `3.0.0-beta.4`, and since them all compilations try to use `3.0.0-beta.4`. It is like some "temporary" build info get stuck somewhere, and only a clean repo will do it right.

**Comment by hood** [comment] 2021-09-20 23:53
Here to report that, in my case, it's not building under both `beta.2` and `beta.4` of `clap 3.0.0`.
using rustc 1.51.0, cargo 1.51.0 ofc

**Comment by george-gca** [comment] 2021-12-21 16:26
Tried again in a new fresh install of updated OS

**Versions:**

- OS: Ubuntu 21.10
- Shell Version: GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
- Cargo Version: 1.53.0

**Additional context**
Installed cargo via apt-get.

Output:
```bash
$ cargo install navi
    Updating crates.io index
  Downloaded navi v2.18.0
error: failed to parse manifest at `/home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

After adding `cargo-features = ["edition2021"]` to the manifest, it threw error with `clap` again

```bash
   Compiling regex v1.5.4
   Compiling clap v3.0.0-rc.7
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-rc.7/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "derive", doc = include_str!("../README.md"))]
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling parking_lot v0.11.2
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `navi v2.18.0`, intermediate artifacts can be found at `/tmp/cargo-installgQNDij`

Caused by:
  build failed
```

Any thoughts?

**Comment by george-gca** [comment] 2021-12-21 16:37
Ok, so I changed cargo installation from `apt` to `rustup` (`curl https://sh.rustup.rs -sSf | sh` as recommended [here](https://doc.rust-lang.org/cargo/getting-started/installation.html)), which gave me `cargo 1.57.0 (b2e52d7ca 2021-10-21)`. Tried to install navi again and

```bash
$ cargo install navi
    Updating crates.io index
  Installing navi v2.18.0
   Compiling libc v0.2.112
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.34
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.82
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling autocfg v1.0.1
   Compiling signal-hook v0.3.13
   Compiling ppv-lite86 v0.2.15
   Compiling parking_lot_core v0.8.5
   Compiling serde_derive v1.0.132
   Compiling smallvec v1.7.0
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.132
   Compiling hashbrown v0.11.2
   Compiling either v1.6.1
   Compiling linked-hash-map v0.5.4
   Compiling anyhow v1.0.51
   Compiling remove_dir_all v0.5.3
   Compiling arrayvec v0.5.2
   Compiling bitflags v1.3.2
   Compiling regex-syntax v0.6.25
   Compiling utf8parse v0.2.0
   Compiling strsim v0.10.0
   Compiling lazy_static v1.4.0
   Compiling termcolor v1.1.2
   Compiling same-file v1.0.6
   Compiling textwrap v0.14.2
   Compiling ryu v1.0.9
   Compiling instant v0.1.12
   Compiling lock_api v0.4.5
   Compiling indexmap v1.7.0
   Compiling yaml-rust v0.4.5
   Compiling walkdir v2.3.2
   Compiling aho-corasick v0.7.18
   Compiling os_str_bytes v6.0.0
   Compiling quote v1.0.10
   Compiling getrandom v0.2.3
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.7.14
   Compiling dirs-sys-next v0.1.2
   Compiling which v4.2.2
   Compiling atty v0.2.14
   Compiling remove_dir_all v0.7.0
   Compiling regex v1.5.4
   Compiling rand_core v0.6.3
   Compiling vte_generate_state_changes v0.1.1
   Compiling directories-next v2.0.0
   Compiling parking_lot v0.11.2
   Compiling clap v3.0.0-rc.7
   Compiling rand_chacha v0.3.1
   Compiling signal-hook-mio v0.2.1
   Compiling shellwords v1.1.0
   Compiling vte v0.10.1
   Compiling rand v0.8.4
   Compiling crossterm v0.22.1
   Compiling strip-ansi-escapes v0.1.1
   Compiling tempfile v3.2.0
   Compiling thiserror-impl v1.0.30
   Compiling edit v0.1.3
   Compiling thiserror v1.0.30
   Compiling serde_yaml v0.8.23
   Compiling navi v2.18.0
error[E0432]: unresolved import `clap::crate_version`
 --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:7:12
  |
7 | use clap::{crate_version, AppSettings, Parser, Subcommand};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot find derive macro `Parser` in this scope
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:58:17
   |
58 | #[derive(Debug, Parser)]
   |                 ^^^^^^
   |
note: `Parser` is imported here, but it is only a trait, without a derive macro
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:7:40
   |
7  | use clap::{crate_version, AppSettings, Parser, Subcommand};
   |                                        ^^^^^^

error: cannot find attribute `clap` in this scope
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:59:3
   |
59 | #[clap(after_help = "\x1b[0;33mMORE INFO:\x1b[0;0m
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:92:3
   |
92 | #[clap(setting = AppSettings::AllowLeadingHyphen)]
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:93:3
   |
93 | #[clap(version = crate_version!())]
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:96:7
   |
96 |     #[clap(short, long, env = env_var::PATH)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:100:7
    |
100 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:104:7
    |
104 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:108:7
    |
108 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:112:7
    |
112 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:116:7
    |
116 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:120:7
    |
120 |     #[clap(short, long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:124:7
    |
124 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:128:7
    |
128 |     #[clap(long)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:132:7
    |
132 |     #[clap(long, possible_values = FINDER_POSSIBLE_VALUES, case_insensitive = true)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:135:7
    |
135 |     #[clap(subcommand)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find derive macro `Parser` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:145:17
    |
145 | #[derive(Debug, Parser)]
    |                 ^^^^^^
    |
note: `Parser` is imported here, but it is only a trait, without a derive macro
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:7:40
    |
7   | use clap::{crate_version, AppSettings, Parser, Subcommand};
    |                                        ^^^^^^

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:150:11
    |
150 |         #[clap(possible_values = FUNC_POSSIBLE_VALUES, case_insensitive = true)]
    |           ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:157:11
    |
157 |         #[clap(subcommand)]
    |           ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:161:7
    |
161 |     #[clap(setting = AppSettings::Hidden)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:167:7
    |
167 |     #[clap(setting = AppSettings::Hidden)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:177:7
    |
177 |     #[clap(setting = AppSettings::Hidden)]
    |       ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:181:11
    |
181 |         #[clap(possible_values = WIDGET_POSSIBLE_VALUES, case_insensitive = true, default_value = "bash")]
    |           ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:186:11
    |
186 |         #[clap(possible_values = INFO_POSSIBLE_VALUES, case_insensitive = true)]
    |           ^^^^
    |
    = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find derive macro `Subcommand` in this scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:191:17
    |
191 | #[derive(Debug, Subcommand)]
    |                 ^^^^^^^^^^
    |
note: `Subcommand` is imported here, but it is only a trait, without a derive macro
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:7:48
    |
7   | use clap::{crate_version, AppSettings, Parser, Subcommand};
    |                                                ^^^^^^^^^^

error[E0599]: no function or associated item named `parse` found for struct `cli::ClapConfig` in the current scope
   --> /home/gca/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.18.0/src/config/cli.rs:141:15
    |
94  | pub(super) struct ClapConfig {
    | ---------------------------- function or associated item `parse` not found for this
...
141 |         Self::parse()
    |               ^^^^^ function or associated item not found in `cli::ClapConfig`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `parse`, perhaps you need to implement it:
            candidate #1: `Parser`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `navi` due to 26 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `navi v2.18.0`, intermediate artifacts can be found at `/tmp/cargo-installiHnOQe`

Caused by:
  build failed
```

**Comment by denisidoro** [comment] 2021-12-21 23:45
Duplicate of #650 

Try running this instead:
```sh
cargo install --locked navi
```

**Comment by orhanbalci** [comment] 2022-01-06 13:13
Hi there. Got the same problem. Is it possible to put this information to readme.

**Closed** 2022-01-12 11:50 UTC
Labels: bug
