### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jarry-jiehu** [denisidoro/navi#397] opened 2020-09-08 07:47 UTC
thread 'main' panicked at 'No more parts in `selections`', src/flows/core.rs:61:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: navi::flows::core::main
  10: navi::handler::handle_config
  11: navi::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by denisidoro** [comment] 2020-09-08 10:15
Hi, could you explain the context here? What did you do prior to this error message? How can I reproduce the problem? Thanks

**Comment by denisidoro** [comment] 2020-10-13 12:53
I'll close this because of the lack of context. Feel free to reopen this if/when you see fit.

**Closed by denisidoro** 2020-10-13 12:53 UTC
Labels: bug
