### ISSUE TITLE
Failing to install using Cargo

### ISSUE THREAD

**Issue by codemeleon** [denisidoro/navi#327] opened 2020-03-31 08:20 UTC
**To Reproduce**

1. Command  `cargo install navi`
2. See error

```
error[E0599]: no method named `as_deref` found for type `std::option::Option<std::string::String>` in the current scope
  --> /home/devil/.cargo/registry/src/github.com-1ecc6299db9ec823/navi-2.2.0/src/flows/core.rs:99:38
   |
99 |         opts.delimiter = o.delimiter.as_deref();
   |                                      ^^^^^^^^ help: there is a method with a similar name: `as_ref`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `navi v2.2.0`, intermediate artifacts can be found at `/tmp/cargo-installwH5OSw`

Caused by:
  Could not compile `navi`.

To learn more, run the command again with --verbose.
```

**Versions:**
 - OS: KDE Neon
 - Shell Version :GNU bash, version 4.4.20(1)-release

**Comment by denisidoro** [comment] 2020-03-31 14:11
Duplicate of https://github.com/denisidoro/navi/issues/321

**Closed by denisidoro** 2020-03-31 14:11 UTC
Labels: bug
