### ISSUE TITLE
navi v2.0.3 panics on any input

### ISSUE THREAD

**Issue by austinjones** [denisidoro/navi#223] opened 2020-03-11 19:26 UTC
**Describe the bug**
I install navi v2.0.3 via homebrew, and I'm running the fish shell.  It looks like it's not finding the cheat files, as any input (git, ls) causes a panic.

**To Reproduce**
1. Install using `brew install denisidoro/tools/navi`
2. Run `navi`
3. Enter `git`, press enter.

**Expected behavior**
Built-in `git` cheats are resolved.

**Screenshots**
```
$ brew install denisidoro/tools/navi
==> Installing navi from denisidoro/tools
==> Downloading https://github.com/denisidoro/navi/releases/download/v2.0.3/navi-x86_64-osx.tar.gz
Already downloaded: /Users/austinjones/Library/Caches/Homebrew/downloads/cf9715a19022091baf31700a252c6b4051a927200d9466b9e5a540310f6c9195--navi-x86_64-osx.tar.gz
🍺  /usr/local/Cellar/navi/2.0.3: 28 files, 2.1MB, built in 3 seconds
$ RUST_BACKTRACE=1 navi                                                               1858ms  Wed Mar 11 15:21:02 2020
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: navi::cmds::core::main
  10: navi::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Versions:**
 - OS: macOS Mojave
 - Shell: fish, version 3.1.0

**Comment by denisidoro** [comment] 2020-03-11 21:10
I found the problem:
```
λ ls -la /usr/local/bin | grep navi
lrwxr-xr-x    1 denis.isidoro  admin        29 Mar 11 18:04 navi -> ../Cellar/navi/2.0.3/bin/navi
```

The symlink created by brew isn't absolute and it's messing with navi internals.

While I don't fix this, there are two solutions:
1. removing the symlink and recreating with an absolute path (to `/usr/local/Cellar/...` for example)
1. Adding `export NAVI_PATH=/usr/local/Cellar/navi/2.0.3/libexec/cheats` to your `.bashrc`-like file

I'm sorry for the inconvenience.

**Comment by denisidoro** [comment] 2020-03-11 21:12
The problem is here, in case anyone wants to help: https://github.com/denisidoro/navi/blob/master/src/filesystem.rs#L14

**Comment by Blquinn** [comment] 2020-03-11 22:38
Hello, having the same issue an a binary I just built from master (ubuntu, zsh). Trying to re-link didn't help for me :( Let me know if I can supply any additional info to help.

**Comment by denisidoro** [comment] 2020-03-11 22:39
Could you please share the result of `navi home`? @Blquinn

**Comment by denisidoro** [comment] 2020-03-11 22:43
Could anyone check if https://github.com/denisidoro/navi/pull/225 is working, please?

**Comment by denisidoro** [comment] 2020-03-11 23:24
It seems this is only happening on OSX. Probably a platform-specific behavior of [fs::read_link](https://doc.rust-lang.org/std/fs/fn.read_link.html).

**Comment by Blquinn** [comment] 2020-03-11 23:29
Hey sure. By the way I'm on ubuntu, not osx.

```
➜  ~ navi home
/home/ben/.navi/target/release
```

```
➜  release git:(master) ✗ RUST_BACKTRACE=1 ./navi
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: navi::cmds::core::main
  15: navi::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:270
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Blquinn** [comment] 2020-03-11 23:35
#255 seems to have restored the search functionality. Upon further inspection, it would appear that the error occurs when the search finds nothing. For example if I type in `alkdsjflkjfwlfkj32lj`, it will return that error.

**Comment by landaire** [comment] 2020-03-12 05:57
I just installed using `brew install denisidoro/tools/navi` and have no issues with neither searches that yeild no results nor the original issue.

**Comment by grebnetiew** [comment] 2020-03-12 09:31
I just built from source on Ubuntu (installed on WSL) as not-root (which stops at an error when it tries to access /usr/local/bin), and then moved the binary over to ~/.bin, on the assumption that this works. It usually does, but this time I got the same error as OP :)

I have limited linux experience, but I'd expect programs that install configuration in my home directory to also look for that information in an absolute location, such as /home/erik/.navi or perhaps (nicer) /home/erik/.config/navi.

If I run the binary in the location I built it, it does work. So made a symlink in .bin instead, which works. Perhaps this helps someone else with the same error.

Perhaps navi could be made more robust by looking for its configuration on an absolute path, or by giving a sensible error message if no configuration can be located :)

**Comment by denisidoro** [comment] 2020-03-12 11:48
Regarding $HOME/.config: that was my initial idea but I'm afraid there's no way to copy files to this folder in a homebrew formula. Does anybody know how?

**Comment by Blquinn** [comment] 2020-03-12 15:23
@denisidoro My guess is that your best bet is to simply set the config directory based on which os you're in (in your rust code). I think that's a separate issue though.

**Comment by austinjones** [comment] 2020-03-12 16:50
@denisidoro I upgraded to v2.0.5 using `brew upgrade navi` and **it works**!

**Comment by denisidoro** [comment] 2020-03-12 17:23
Closing this because the main issue seems to be fixed. I'm aware the current way navi deals with folders is error-prone but I believe we can tackle that in more specific, future issues.

**Closed by denisidoro** 2020-03-12 17:23 UTC
Labels: bug
